home_page/urls.py
from django.urls import path, reverse_lazy
from . import views

from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

app_name = "home_page"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("delete", views.delete_user, name="delete_account"),
    path("user/<str:user>", views.user_view, name="account"),
    path("change-password", views.change_password, name="change_password"),
    path("privacy-statement", views.privacy_statement, name="privacy"),

    path("password-reset", PasswordResetView.as_view(template_name="home_page\password_reset.html", email_template_name="home_page\password_reset_email.html", success_url=reverse_lazy("home_page:password_reset_done")), name="password_reset"),

    path("password-reset-confirm/<uidb64>/<token>", PasswordResetConfirmView.as_view(template_name="home_page\password_reset_confirm.html", success_url=reverse_lazy("home_page:password_reset_complete")), name="password_reset_confirm"),

    path("password-reset/done", PasswordResetDoneView.as_view(template_name="home_page\password_reset_done.html"), name="password_reset_done"),

    path("password-reset-complete", PasswordResetCompleteView.as_view(template_name="home_page\password_reset_complete.html"), name="password_reset_complete")
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from environs import Env

env = Env()
env.read_env()

urlpatterns = [
    path(env("ADMIN"), admin.site.urls),
    path('', include("home_page.urls")),
    path('vocabulary/', include("vocab_trainer.urls"))
]

vocab_trainer/urls.py
from django.urls import path
from . import views

app_name = "vocab_trainer"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add"),
    path("test", views.test, name="test"),
    path("translations", views.translations_table, name="translations")
]

vocab_trainer/models.py
from django.db import models
from django.core.validators import MaxValueValidator
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

WORD_MAX_LENGTH = 64

class KnownLanguageNoun(models.Model):

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    known_language_noun = models.CharField(max_length=WORD_MAX_LENGTH)
    
    class Meta:
        abstract = True
        ordering = ["known_language_noun"]

    def __str__(self):
        return f"{self.known_language_noun}"
    
    
class TargetLanguageNoun(models.Model):

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    target_language_noun = models.CharField(max_length=WORD_MAX_LENGTH)
    last_test = models.DateField(auto_now=True)
    number_of_tests = models.PositiveIntegerField(default=0)
    correct_tests = models.PositiveIntegerField(default=0)
    percentage_correct = models.PositiveIntegerField(
        default=0,
        validators=[MaxValueValidator(100)])

    class Meta:
        abstract = True
        ordering = ["target_language_noun"]
    

class EnglishNoun(KnownLanguageNoun):
    
    ARTICLES = [
        ("The", "The")
        ]
    article = models.CharField(max_length=3, default="The")


class GermanNoun(TargetLanguageNoun):
    
    ARTICLES = [
        ("Der", "Der"),
        ("Die", "Die"),
        ("Das", "Das")
    ]
    article = models.CharField(max_length=3, choices=ARTICLES)
    translations = models.ManyToManyField(EnglishNoun)

    def __str__(self):
        return f"{self.article} {self.target_language_noun}"

vocab_trainer/views.py
from django.shortcuts import render
from .models import GermanNoun
from django.contrib.auth.models import User
from .language_forms import NewNounForm, TranslateToKnown, TranslateToTarget
from .language_queries import add_noun_to_db, select_noun_to_test, check_user_answer, update_answer_stats, create_test_response_dict

INDEX_TEMPLATE = "vocab_trainer/index.html"
ADD_TEMPLATE = "vocab_trainer/add.html"
TEST_TEMPLATE = "vocab_trainer/test.html"
TRANSLATIONS_TEMPLATE = "vocab_trainer/translations.html"

def index(request):
    return render(request, INDEX_TEMPLATE)


def add(request):
    user = request.user
    if request.method == "POST" and user.is_authenticated:
        new_noun_form = NewNounForm(request.POST)

        if new_noun_form.is_valid():
            _, message = add_noun_to_db(new_noun_form, user)
            return render(request, ADD_TEMPLATE, {
                "form": NewNounForm(),
                "message": message
            })
        else:
            return render(request, ADD_TEMPLATE, {
                "form": new_noun_form
            })
    return render(request, ADD_TEMPLATE, {
        "form": NewNounForm()
    })


def test(request):

    user = request.user

    if not user.is_authenticated:
        user = User.objects.get(username="GuestUser")

    if request.method == "POST":

        if request.POST["translation_to"] == "to_known":
            to_known = True
            answer_form = TranslateToKnown(request.POST)

        elif request.POST["translation_to"] == "to_target":
            to_known = False
            answer_form = TranslateToTarget(request.POST)

        if answer_form.is_valid():
            translations, user_answer_correct = check_user_answer(answer_form, user)

            if not user.username == "GuestUser":
                update_answer_stats(answer_form,
                                    user_answer_correct,
                                    to_known, user)

            if not user_answer_correct:
                return render(
                    request, 
                    TEST_TEMPLATE, 
                    create_test_response_dict(answer_form, translations, to_known, valid_submission=True)
                )
        else:
            return render(
                request, 
                TEST_TEMPLATE,
                create_test_response_dict(answer_form, translations, to_known, valid_submission=False)
            )

    return render(request, TEST_TEMPLATE, select_noun_to_test(user))


def translations_table(request):

    if request.user.is_authenticated:
        german_nouns = GermanNoun.objects.filter(user=request.user).values()
        return render(request, TRANSLATIONS_TEMPLATE, {
            "nouns": german_nouns
        })
    else:
        return render(request, TRANSLATIONS_TEMPLATE)


def reference_tables(request):
    ...

vocab_trainer/templates/vocab_trainer/add.html
{% extends "vocab_trainer/layout.html" %}

{% block body %}

    <h3>Add to Your Vocabulary</h3>
    <form action="{% url 'vocab_trainer:add' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>

    {% if message %}
        <p>{{ message }}</p>
    {% endif %}

    <a href="{% url 'vocab_trainer:index' %}">Return</a>

{% endblock %}

vocab_trainer/templates/vocab_trainer/index.html
{% extends "vocab_trainer/layout.html" %}

{% block body %}

    <a href="{% url 'vocab_trainer:add' %}">Add vocabulary</a>
    <a href="{% url 'vocab_trainer:test' %}">Test vocabulary</a>
    <a href="{% url 'home_page:index' %}">Home Page</a>
    {% if user.is_authenticated %}
        <a href="{% url 'home_page:logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'home_page:login' %}">Login</a>
    {% endif %}
    <a href="{% url 'vocab_trainer:translations' %}">Vocabulary Table</a>

{% endblock %}

vocab_trainer/templates/vocab_trainer/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>German</title>
    <link rel="stylesheet" href="{% static 'vocab_trainer/css/structure.css' %}">
</head>
<body>
    <h1>Language</h1>
    <div>
        {% block body %}{% endblock %}
    </div>
</body>
</html>

vocab_trainer/templates/vocab_trainer/test.html
{% extends "vocab_trainer/layout.html" %}

{% block body %}

    <h3>Test Your Vocabulary</h3>

    {% if not no_vocabulary %}

        {% if is_translation_to_known %}
            <p>Translate the word below to English</p>
            <p>{{ question_article }} {{ question_noun }}</p>
        {% else %}
            <p>Translate the word below to German</p>
            <p>{{ question_noun }}</p>
        {% endif %}

        {% if add_check_answer_button %}
            <form action="{% url 'vocab_trainer:test' %}" method="POST">
                {% csrf_token %}
                {{ answer_form }}
                <input type="submit" value="Check Answer">
            </form>
        {% else %}
            <form action="{% url 'vocab_trainer:test' %}" method="POST">
                {{ answer_form }}
            </form>
            <form action="{% url 'vocab_trainer:test' %}" method="GET">
                <input type="submit" value="Next Question">
            </form>
        {% endif %}

    {% endif %}

    {% if response_message %}
        <p>{{ response_message }}</p>
    {% endif %}

    {% if guest_user %}
        <p>Guest user</p>
    {% endif %}

    <a href="{% url 'vocab_trainer:index' %}">Return</a>
    
{% endblock %}

vocab_trainer/templates/vocab_trainer/translations.html
{% extends 'vocab_trainer/layout.html' %}

{% block body %}
    <table>
        <tr>
            <th>ID</th>
            <th>User</th>
            <th>Article</th>
            <th>Noun</th>
            <th>Last Tested</th>
            <th>Percentage Correct</th>
        </tr>
        {% for noun in nouns %}
            <tr>
                <td>{{ noun.id }}</td>
                <td>{{ noun.user_id }}</td>
                <td>{{ noun.article }} </td>
                <td>{{ noun.target_language_noun }}</td>
                <td>{{ noun.last_test }}</td>
                <td>{{ noun.percentage_correct }}</td>
            </tr>
        {% endfor %}
    </table>

    <a href="{% url 'vocab_trainer:index' %}">Return</a>

{% endblock %}