home_page/urls.py
from django.urls import path, reverse_lazy
from . import views

from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

app_name = "home_page"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("delete", views.delete_user, name="delete_account"),
    path("user/<str:user>", views.user_view, name="account"),
    path("change-password", views.change_password, name="change_password"),
    path("privacy-statement", views.privacy_statement, name="privacy"),

    path("password-reset", PasswordResetView.as_view(template_name="home_page\password_reset.html", email_template_name="home_page\password_reset_email.html", success_url=reverse_lazy("home_page:password_reset_done")), name="password_reset"),

    path("password-reset-confirm/<uidb64>/<token>", PasswordResetConfirmView.as_view(template_name="home_page\password_reset_confirm.html", success_url=reverse_lazy("home_page:password_reset_complete")), name="password_reset_confirm"),

    path("password-reset/done", PasswordResetDoneView.as_view(template_name="home_page\password_reset_done.html"), name="password_reset_done"),

    path("password-reset-complete", PasswordResetCompleteView.as_view(template_name="home_page\password_reset_complete.html"), name="password_reset_complete")
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from environs import Env

env = Env()
env.read_env()

urlpatterns = [
    path(env("ADMIN"), admin.site.urls),
    path('', include("home_page.urls")),
    path('vocabulary/', include("vocab_trainer.urls"))
]

home_page/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    email = models.EmailField(blank=True, unique=True)

home_page/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class LoginForm(forms.Form):

    username = forms.CharField(label="Username")
    password = forms.CharField(widget=forms.PasswordInput)


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = (
            "email",
            "username"
        )


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = (
            "email",
            "username"
        )

home_page/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

from .forms import LoginForm, CustomUserCreationForm

INDEX_TEMPLATE = "home_page/index.html"
REGISTER_TEMPLATE = "home_page/register.html"
LOGIN_TEMPLATE = "home_page/login.html"
ACCOUNT_TEMPLATE = "home_page/account.html"
DELETE_ACCOUNT_TEMPLATE = "home_page/delete_account.html"
CHANGE_PASSWORD_TEMPLATE = "home_page/change_password.html"
PRIVACY_STATEMENT_TEMPLATE = "home_page/privacy.html"

def index(request):
    return render(request, INDEX_TEMPLATE)

def register(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('home_page:account', 
                                            kwargs={"user": request.user.username})
        )
    if request.method == "POST":
        new_user_form = CustomUserCreationForm(request.POST)
        if new_user_form.is_valid():
            user = get_user_model().objects.create_user(new_user_form.cleaned_data["username"], 
                                                        new_user_form.cleaned_data["email"], 
                                                        new_user_form.cleaned_data["password1"])
            if user:
                login(request, user)
                return HttpResponseRedirect(reverse(
                    "home_page:account", 
                    args=[new_user_form.cleaned_data["username"]]
                    )
                )
        return render(request, REGISTER_TEMPLATE, {
            "form": new_user_form
        })
    return render(request, REGISTER_TEMPLATE, {
        "form": CustomUserCreationForm()
    })

def login_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('home_page:account', 
                                            kwargs={"user": request.user.username})
        )
    if request.method == "POST":
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data["username"]
            password = login_form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return HttpResponseRedirect(reverse("home_page:account", 
                                                    kwargs={"user": username})
                )
        return render(request, 
                      LOGIN_TEMPLATE, 
                      {"form": login_form, "message": "Details did not match an existing user"}
        )
    return render(request, LOGIN_TEMPLATE, {
        "form": LoginForm()
    })

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("home_page:index"))

def user_view(request, user):
    if request.user.is_authenticated and user == request.user.username:
        return render(request, ACCOUNT_TEMPLATE)
    elif get_user_model().objects.filter(username=user).exists():
        return HttpResponseRedirect(reverse("home_page:login"))
    return HttpResponseRedirect(reverse("home_page:index"))

def delete_user(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("home_page:login"))
    if request.method == "POST":
        user = get_user_model().objects.filter(username=request.user)
        user.delete()
        return render(request, DELETE_ACCOUNT_TEMPLATE) # redirect
    return render(request, DELETE_ACCOUNT_TEMPLATE, {"check_for_delete": True})

def change_password(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("home_page:login"))
    
    if request.method == "POST":
        change_password_form = PasswordChangeForm(request.user, request.POST)
        if not change_password_form.is_valid():
            print(change_password_form.errors)
            print(change_password_form.non_field_errors())
            return render(request, CHANGE_PASSWORD_TEMPLATE, {"form": change_password_form})

        user = change_password_form.save()
        update_session_auth_hash(request, user)
        return render(request, CHANGE_PASSWORD_TEMPLATE) # redirect

    return render(request, CHANGE_PASSWORD_TEMPLATE, {"form": PasswordChangeForm(request.user)})

def privacy_statement(request):
    return render(request, PRIVACY_STATEMENT_TEMPLATE)

home_page/templates/home_page/account.html
{% extends 'home_page/sub_page_layout.html' %}

{% block header %}Hi, {{ request.user.username }}{% endblock %}

{% block options-list %}
    <li><a class="nav-link home-page-link" href="{% url 'home_page:index' %}">Home</a></li>
    <li><a class="nav-link logout-link" href="{% url 'home_page:logout' %}">Logout</a></li>
    <li><a class="nav-link delete-account-link" href="{% url 'home_page:delete_account' %}">Delete Account</a></li>
    <li><a class="nav-link change-password-link" href="{% url 'home_page:change_password' %}">Change Password</a></li>
{% endblock %}

home_page/templates/home_page/change_password.html
{% extends 'home_page/sub_page_layout.html' %}

{% block header %}Change your password{% endblock %}

{% block form %}
    {% if form %}
    <form id="change-password-form" class="main-form" action="{% url 'home_page:change_password' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input class="submit-btn" id="confirm-change-password-btn" type="submit" value="Change Password">
    </form>
    {% else %}
    <p id="password-changed-confirm-msg" class="sub-page-text">Password successfully changed</p>
    {% endif %}
{% endblock %}

{% block options-list %}
    <li><a class="nav-link home-page-link" href="{% url 'home_page:index' %}">Home</a></li>
    <li><a class="nav-link home-page-link" href="{% url 'home_page:account' user=user %}">Back to account</a></li>
{% endblock %}

home_page/templates/home_page/delete_account.html
{% extends "home_page/sub_page_layout.html" %}

{% block header %}Delete account{% endblock %}

{% block form %}
    {% if check_for_delete %}
        <p id="confirm-delete-msg" class="helptext">Are you sure you want to delete your account?</p>
        <form class="main-form" action="{% url 'home_page:delete_account' %}" method="POST">
            {% csrf_token %}
            <input class="submit-btn confirm-delete-btn" type="submit" value="Confirm">
        </form>
    {% else %}
        <p id="account-deleted-msg" class="helptext">Account deleted</p>
    {% endif %}
{% endblock %}

{% block options-list %}
    {% if check_for_delete %}
        <li><a class="nav-link cancel-link" href="{% url 'home_page:account' user=user %}">Cancel</a></li>
    {% else %}
        <li><a class="nav-link home-page-link" href="{% url 'home_page:index' %}">Home</a></li>
    {% endif %}
{% endblock %}

home_page/templates/home_page/index.html
{% extends 'home_page/layout.html' %}
{% load static %}

{% block navbar %}
    {% if user.is_authenticated %}
        <li class="nav-menu-list-item">
            <a class="nav-link" href="{% url 'home_page:account' user=user %}">Account</a>
        </li>
    {% else %}
        <li class="nav-menu-list-item">
            <a class="nav-link" href="{% url 'home_page:login' %}">Login</a>
        </li>
        <li class="nav-menu-list-item">
            <a class="nav-link" href="{% url 'home_page:register' %}">Register</a>
        </li>
    {% endif %}
{% endblock %}

{% block body %}
    <section class="section-main section-header">
        <div class="section-header-cntr">
            <div class="header-text-cntr">
                <p>Hi. I'm <span>Phil</span>.</p>
                <p>A full stack <span>developer</span> and <span>data analyst</span>.</p>
            </div>
            <!-- main line -->
                <svg
                    class="mainline"
                    viewBox="-1 -1 411 48"
                    version="1.1"
                    id="svg5"
                    xmlns:xlink="http://www.w3.org/1999/xlink"
                    xmlns="http://www.w3.org/2000/svg"
                    xmlns:svg="http://www.w3.org/2000/svg">
                    <defs
                        id="defs2">
                        <linearGradient
                        id="linearGradient1249">
                        <stop
                            style="stop-color:#7700ff;stop-opacity:1;"
                            offset="0"
                            id="stop1245" />
                        <stop
                            style="stop-color:#cc00ff;stop-opacity:1;"
                            offset="1"
                            id="stop1247" />
                        </linearGradient>
                        <linearGradient
                        xlink:href="#linearGradient1249"
                        id="linearGradient1253"
                        x1="2.3044975"
                        y1="47.17728"
                        x2="407.42432"
                        y2="4.3343587"
                        gradientUnits="userSpaceOnUse" />
                        <linearGradient
                        xlink:href="#linearGradient1249"
                        id="linearGradient1363"
                        gradientUnits="userSpaceOnUse"
                        x1="2.3044975"
                        y1="47.17728"
                        x2="407.42432"
                        y2="4.3343587" />
                    </defs>
                    <g
                        id="layer1"
                        style="fill:none;fill-opacity:1;stroke:url(#linearGradient1253)"
                        transform="translate(-0.8094975,-2.6429396)">
                        <path
                        style="fill:none;fill-opacity:1;stroke:url(#linearGradient1363);stroke-width:5;stroke-linecap:round;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
                        d="M 2.3044975,47.17728 C 384.77684,-25.825236 402.15065,14.653475 408.19775,21.366883"
                        id="path1332" />
                    </g>
                </svg>
            
        </div>
    </section>

    <section class="section-main" id="section-skills">
        <div class="section-main-cntr">
            <h2 class="section-heading">Skills</h2>
            <div class="skills-list-cntr">
                <ul class="skills-list">
                    <li>
                        <div class="skills-cntr">
                            <img class="skills-logo" src="{% static '\home_page\images\python-original.svg' %}">
                            <p>Python</p>
                        </div>
                    </li>
                    <li>
                        <div class="skills-cntr">
                            <img class="skills-logo" src="{% static '\home_page\images\django-original.svg' %}">
                            <p>Django</p>
                        </div>
                    </li>
                    <li>
                        <div class="skills-cntr">
                            <img class="skills-logo" src="{% static '\home_page\images\javascript-original.svg' %}">
                            <p>JavaScript</p>
                        </div>
                    </li>
                    <li>
                        <div class="skills-cntr">
                            <img class="skills-logo" src="{% static '\home_page\images\css-original.svg' %}">
                            <p>CSS</p>
                        </div>
                    </li>
                    <li>
                        <div class="skills-cntr">
                            <img class="skills-logo" src="{% static '\home_page\images\sass-original.svg' %}">
                            <p>Sass</p>
                        </div>
                    </li>
                    <li>
                        <div class="skills-cntr">
                            <img class="skills-logo" src="{% static '\home_page\images\html-original.svg' %}">
                            <p>HTML</p>
                        </div>
                    </li>
                    <li>
                        <div class="skills-cntr">
                            <img class="skills-logo" src="{% static '\home_page\images\react-original.svg' %}">
                            <p>React</p>
                        </div>
                    </li>
                    <li>
                        <div class="skills-cntr">
                            <img class="skills-logo" src="{% static '\home_page\images\git-original.svg' %}">
                            <p>Git</p>
                        </div>
                    </li>
                    <li>
                        <div class="skills-cntr">
                            <img class="skills-logo" src="{% static '\home_page\images\c-sharp-original.svg' %}">
                            <p>C#</p>
                        </div>
                    </li>
                    <li>
                        <div class="skills-cntr">
                            <img class="skills-logo" src="{% static '\home_page\images\sql-original.svg' %}">
                            <p>SQL</p>
                        </div>
                    </li>
                    <li>
                        <div class="skills-cntr">
                            <img class="skills-logo" src="{% static '\home_page\images\numpy-original.svg' %}">
                            <p>Numpy</p>
                        </div>
                    </li>
                    <li>
                        <div class="skills-cntr">
                            <img class="skills-logo" src="{% static '\home_page\images\pandas-original.svg' %}">
                            <p>Pandas</p>
                        </div>
                    </li>
                    <li>
                        <div class="skills-cntr">
                            <img class="skills-logo" src="{% static '\home_page\images\scikit-learn-original.svg' %}">
                            <p>Scikit-learn</p>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </section>

    <section class="section-main" id="section-about">
        <div class="section-main-cntr">
            <h2 class="section-heading">About</h2>
            <div class="about-text">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu arcu urna. Fusce tempus dapibus eros eget convallis. Praesent elit metus, scelerisque nec libero et, pulvinar mollis mauris. Vestibulum non orci vel nisl faucibus fermentum eu a augue.</p> 
                <p>Habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce ante turpis, posuere quis suscipit at, semper ut magna. Suspendisse eleifend orci eu sapien venenatis, at elementum est sollicitudin. Mauris ultrices eros eget velit interdum eleifend. Mauris tincidunt, ligula eget tincidunt bibendum, enim felis mattis sapien, eu mollis nibh risus sit amet ante. Integer luctus at elit a.</p>
            </div>
        </div>
    </section>

    <section class="section-main section-apps" id="section-apps">
        <div class="section-main-cntr apps-cntr">
            <h2 class="section-heading">Apps</h2>
        </div>
    </section>
    
{% endblock %}

home_page/templates/home_page/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>PBDE</title>
        <link rel="stylesheet" href="{% static 'home_page/css/structure.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700&display=swap" rel="stylesheet">
        <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
        <script defer src="{% static 'home_page/javascript/layout.js' %}"></script>
    </head>
    <body>
        <menu class="nav-menu-bar">
            <div>
               <a class="home-link nav-link" href="{% url 'home_page:index' %}">PBDE</a>
            </div>
            <ul class="nav-menu-list">
                <li class="nav-menu-list-item">
                    <a class="nav-link" href="{% url 'home_page:index' %}#section-skills">About</a>
                </li>
                <li class="nav-menu-list-item">
                    <a class="nav-link" href="{% url 'home_page:index' %}#section-apps">Apps</a>
                </li>
                {% block navbar %}{% endblock %}
            </ul>
            <button class="nav-menu-btn">
                <ion-icon class="nav-menu-icon" name="menu-outline"></ion-icon>
                <ion-icon class="nav-menu-icon" name="close-outline"></ion-icon>
            </button>
        </menu>
        <div class="main-block">
            {% block body %}{% endblock %}
        </div>
    </body>
</html>

home_page/templates/home_page/login.html
{% extends 'home_page/sub_page_layout.html' %}

{% block header %}Login{% endblock %}

{% block form %}
    {% if message %}
        <p class="form-error-msg">{{ message }}</p>
    {% endif %}
    <form class="main-form" action="{% url 'home_page:login' %}" method="POST" id="login-form">
        {% csrf_token %}
        {{ form }}
        <input class="submit-btn" type="submit" value="Login" id="login-btn">
    </form>
{% endblock %}

{% block options-list %}
    <li><a class="nav-link register-page-link" href="{% url 'home_page:register' %}">Register</a></li>
    <li><a class="nav-link home-page-link" href="{% url 'home_page:index' %}">Home</a></li>
    <li><a class="nav-link forgotten-password-link" href="{% url 'home_page:password_reset' %}">Forgotten Password</a></li>
{% endblock %}

home_page/templates/home_page/password_reset.html
{% extends "home_page\sub_page_layout.html" %}

{% block header %}Forgotten password{% endblock %}

{% block form %}
    <form class="main-form" method="POST">
        {% csrf_token %}
        {{ form }}
        <input class="submit-btn" id="request-password-btn" type="submit">
    </form>
{% endblock %}

home_page/templates/home_page/password_reset_complete.html
{% extends "home_page\sub_page_layout.html" %}

{% block header %}Password updated{% endblock %}

{% block form %}
    <p id="password-changed-confirm-msg" class="helptext">Password successfully changed</p>
{% endblock %}

{% block options-list %}
    <a id="login-link" class="nav-link" href="{% url 'home_page:login' %}">Return to login page</a>
{% endblock %}

home_page/templates/home_page/password_reset_confirm.html
{% extends 'home_page/sub_page_layout.html' %}

{% block header %}Create new password{% endblock %}

{% block form %}
    <form class="main-form" method="POST">
        {% csrf_token %}
        {{ form }}
        <input class="submit-btn" id="password-reset-btn" type="submit">
    </form>
{% endblock %}

home_page/templates/home_page/password_reset_done.html
{% extends 'home_page/sub_page_layout.html' %}

{% block header %}Email sent{% endblock %}

{% block form %}
    <p id="password-email-sent-msg" class="sub-page-text">If the email provided matches a registered email address, an email containing instructions for resetting your password will be sent.</p>
{% endblock %}

home_page/templates/home_page/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'home_page:password_reset_confirm' uidb64=uid token=token %}

home_page/templates/home_page/privacy.html
{% extends 'home_page/sub_page_layout.html' %}

{% block header %}Privacy Statement{% endblock %}

{% block form %}
    <p class="privacy-text">This Privacy Notice explains how we collect, use, and safeguard your information when you visit this website.</p>
    <h3 class="privacy-sub-heading">Information We Collect</h3>
    <p class="privacy-text">If you do not register on the site, no information about you is collected or used. If you do register, we only collect information that is necessary for you to register and make full use of our website's services. When you register on our site, we collect your username and email address. This information is solely used to create and manage your account, authenticate you when you log in, and provide you with access to our services.</p>
    <h3 class="privacy-sub-heading">Use of Your Information</h3>
    <p class="privacy-text">The information we collect is used solely to provide you with access to our services. Your username and email address are used for account management purposes. We do not share this information with any third parties.</p>
    <h3 class="privacy-sub-heading">Your Rights Regarding Your Information</h3>
    <p class="privacy-text">You can see all the information that is held about you by visiting your account page after you register. You can delete your account at any time via your account page, which will result in the complete removal of your data from our system.</p>
    <h3 class="privacy-sub-heading">Data Security</h3>
    <p class="privacy-text">We have implemented appropriate technical and organizational security measures designed to protect the security of any personal information we process. However, please note that no method of transmission over the Internet, or method of electronic storage is 100% secure and we cannot guarantee absolute security.</p>
{% endblock %}

{% block options-list %}
    {% if user.is_authenticated %}
        <li><a class="nav-link home-page-link" href="{% url 'home_page:index' %}">Home</a></li>
    {% else %}
        <li><a class="nav-link register-page-link" href="{% url 'home_page:register' %}">Register</a></li>
    {% endif %}
{% endblock %}

home_page/templates/home_page/register.html
{% extends 'home_page/sub_page_layout.html' %}

{% block header %}Sign up{% endblock %}

{% block form %}

    <form class="main-form" action="{% url 'home_page:register' %}" method="POST" id="create-user-form">
        {% csrf_token %}
        {{ form }}
        <input class="submit-btn" type="submit" value="Sign up" id="register-btn">
    </form>

{% endblock %}

{% block options-list %}
    <li><a class="nav-link login-page-link" href="{% url 'home_page:login' %}">Login</a></li>
    <li><a class="nav-link home-page-link" href="{% url 'home_page:index' %}">Home</a></li>
    <li><a class="nav-link privacy-statement-link" href="{% url 'home_page:privacy' %}">Privacy Statement</a></li>
{% endblock %}

home_page/templates/home_page/sub_page_layout.html
{% extends 'home_page/layout.html' %}

{% block body %}
    <section class="section-sub-page">
        <div class="sub-page-cntr">
            <h2 class="section-heading sub-page-heading">{% block header %}{% endblock %}</h2>
            {% block form %}{% endblock %}
            <ul class="sub-page-options-list">
                {% block options-list %}{% endblock %}
            </ul>
        </div>
    </section>
{% endblock %}